name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::$(date +%Y-%m-%d)"

  build:
    runs-on: ubuntu-latest
    needs: generate-tag
    steps:
    - name: Print Version
      run: echo ${{ needs.generate-tag.outputs.output1 }}
    
#    - name: Docker Login
#      # You may pin to the exact commit or the version.
#      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
#      uses: docker/login-action@v2.0.0
#      with:
#        username: pollutionmonster
#        # Password or personal access token used to log against the Docker registry
#        password: ${{ secrets.DOCKER_HUB_PAT }}
#    
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build -f "Checkers/Checkers/Dockerfile" -t pollutionmonster/checkers:${{ env.vtag }} --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=Checkers" "Checkers"
#      
#    - name: Push Docker Image
#      run: docker push pollutionmonster/checkers:${{ env.VERSION }}
