name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -f .\Checkers\Dockerfile --force-rm -t checkers --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=Checkers" .\Checkers
      working-directory: Checkers
